version: '3.7'

services:
  bot:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      OAUTH_TOKEN: ${OAUTH_TOKEN}
      CATALOG_ID: ${CATALOG_ID}